import type {
  AppointmentDTO,
  ContactInfoDTO,
  DashboardDTO,
  EventDetailDTO,
  EventListItemDTO,
  EventTemplateDTO,
  FormFieldConfigDTO,
  HoldResponseDTO,
  PartitionLandingDTO,
  PortalDocumentDTO,
  UserAccountDTO,
  UserGroupDTO,
  UserPartitionDTO,
} from './index';

const systemFields: FormFieldConfigDTO[] = [
  {
    fieldKey: 'participant_name',
    labelEn: 'Full Name in English (Legal name)',
    labelZh: '英文全名（與法律文件相同）',
    fieldType: 'TEXT',
    required: true,
    visibleInERP: true,
    visibleInECP: true,
    visibleInEAP: true,
    sortOrder: 10,
    isSystem: false,
    placeholderEn: 'Chan Tai Man',
  },
  {
    fieldKey: 'staff_number',
    labelEn: 'Staff Number',
    labelZh: '員工編號',
    fieldType: 'TEXT',
    required: true,
    visibleInERP: true,
    visibleInECP: true,
    visibleInEAP: true,
    sortOrder: 20,
    isSystem: false,
    placeholderEn: '43791500',
  },
  {
    fieldKey: 'medical_card_number',
    labelEn: 'Medical Card Number',
    labelZh: '醫療卡號碼',
    fieldType: 'TEXT',
    required: false,
    visibleInERP: true,
    visibleInECP: true,
    visibleInEAP: true,
    sortOrder: 30,
    isSystem: false,
  },
  {
    fieldKey: 'hkid_prefix',
    labelEn: 'First 4 digits of HKID or Passport',
    labelZh: '香港身份證／護照首四位字元',
    fieldType: 'TEXT',
    required: false,
    visibleInERP: true,
    visibleInECP: true,
    visibleInEAP: true,
    sortOrder: 40,
    isSystem: false,
  },
  {
    fieldKey: 'registered_email',
    labelEn: 'Registered eMail',
    labelZh: '登記電郵',
    fieldType: 'EMAIL',
    required: true,
    visibleInERP: true,
    visibleInECP: true,
    visibleInEAP: true,
    sortOrder: 50,
    isSystem: true,
    placeholderEn: 'employee@hsbc.com.hk',
  },
  {
    fieldKey: 'mobile_number',
    labelEn: 'Mobile No.',
    labelZh: '手提電話號碼',
    fieldType: 'MOBILE',
    required: true,
    visibleInERP: true,
    visibleInECP: true,
    visibleInEAP: true,
    sortOrder: 60,
    isSystem: true,
    placeholderEn: '67180938',
  },
];

export const partitions: UserPartitionDTO[] = [
  {
    documentId: 'partition-hsbc-flu',
    code: 'HSBC-FLU',
    description: 'HSBC annual flu vaccination partition',
    slug: 'hsbc-flu',
    status: 'ACTIVE',
    remarks: 'Primary HSBC public ERP partition.',
    userGroupCodes: ['QHMS', 'HSBC-HR'],
    templateDocumentId: 'template-hsbc-2026-flu',
    templateName: 'HSBC 2026 Flu Vaccination Template',
    logo: {
      documentId: 'media-hsbc-logo',
      name: 'hsbc-logo.png',
      url: '/uploads/hsbc-logo.png',
      alternativeText: 'HSBC logo',
      width: 320,
      height: 120,
    },
    banners: [
      {
        documentId: 'media-hsbc-banner',
        name: 'hsbc-banner.png',
        url: '/uploads/hsbc-banner.png',
        alternativeText: 'HSBC flu vaccination banner',
        width: 1440,
        height: 480,
      },
    ],
  },
  {
    documentId: 'partition-hase-flu',
    code: 'HASE-FLU',
    description: 'HASE staff flu vaccination partition',
    slug: 'hase-flu',
    status: 'ACTIVE',
    remarks: 'HASE staff ERP entry scope.',
    userGroupCodes: ['QHMS', 'HASE-HR'],
    templateDocumentId: 'template-hsbc-2026-flu',
    templateName: 'HSBC 2026 Flu Vaccination Template',
    banners: [],
  },
];

export const groups: UserGroupDTO[] = [
  {
    documentId: 'group-qhms',
    code: 'QHMS',
    description: 'QHMS platform client scope',
    remarks: 'Shared access scope',
    status: 'ACTIVE',
    partitionCodes: ['HSBC-FLU', 'HASE-FLU'],
    partitionDocumentIds: ['partition-hsbc-flu', 'partition-hase-flu'],
    portalUserDocumentIds: [],
    portalUsers: [],
  },
  {
    documentId: 'group-hsbc-hr',
    code: 'HSBC-HR',
    description: 'HSBC HR portal users',
    remarks: 'HSBC client portal access',
    status: 'ACTIVE',
    partitionCodes: ['HSBC-FLU'],
    partitionDocumentIds: ['partition-hsbc-flu'],
    portalUserDocumentIds: ['user-hsbc-karen'],
    portalUsers: [
      {
        documentId: 'user-hsbc-karen',
        username: 'karen.wong',
        email: 'karen.wong@hsbc.com.hk',
        status: 'ACTIVE',
        portalRole: 'CLIENT_HR',
      },
    ],
  },
  {
    documentId: 'group-hase-hr',
    code: 'HASE-HR',
    description: 'HASE HR portal users',
    remarks: 'HASE client portal access',
    status: 'ACTIVE',
    partitionCodes: ['HASE-FLU'],
    partitionDocumentIds: ['partition-hase-flu'],
    portalUserDocumentIds: [],
    portalUsers: [],
  },
];

export const userAccounts: UserAccountDTO[] = [
  {
    documentId: 'user-admin-amy',
    username: 'amy.cheng',
    email: 'amy.cheng@qhms.com',
    status: 'ACTIVE',
    portalRole: 'ADMIN',
    confirmed: true,
    provider: 'local',
    roleName: 'Authenticated',
    roleType: 'authenticated',
    lastLoginAt: '2026-04-16T09:15:00.000Z',
    userGroupCodes: [],
  },
  {
    documentId: 'user-hsbc-karen',
    username: 'karen.wong',
    email: 'karen.wong@hsbc.com.hk',
    status: 'ACTIVE',
    portalRole: 'CLIENT_HR',
    confirmed: true,
    provider: 'local',
    roleName: 'Authenticated',
    roleType: 'authenticated',
    lastLoginAt: '2026-04-16T02:35:00.000Z',
    userGroupCodes: ['HSBC-HR'],
  },
];

export const templates: EventTemplateDTO[] = [
  {
    documentId: 'template-hsbc-2026-flu',
    name: 'HSBC 2026 Flu Vaccination Template',
    description: 'Annual employee flu vaccination template',
    partitionCodes: ['HSBC-FLU', 'HASE-FLU'],
    partitionDocumentIds: ['partition-hsbc-flu', 'partition-hase-flu'],
    fieldCount: systemFields.length,
    fields: systemFields,
  },
];

const hsbcEventDates = [
  {
    documentId: 'event-date-0901',
    date: '2026-09-01',
    enabled: true,
    slots: [
      {
        documentId: 'slot-0901-0900',
        startTime: '09:00',
        endTime: '09:30',
        enabled: true,
        quota: 10,
        usedCount: 2,
        holdCount: 1,
        remaining: 7,
      },
      {
        documentId: 'slot-0901-0930',
        startTime: '09:30',
        endTime: '10:00',
        enabled: true,
        quota: 10,
        usedCount: 4,
        holdCount: 0,
        remaining: 6,
      },
      {
        documentId: 'slot-0901-1000',
        startTime: '10:00',
        endTime: '10:30',
        enabled: false,
        quota: 10,
        usedCount: 0,
        holdCount: 0,
        remaining: 10,
      },
    ],
  },
  {
    documentId: 'event-date-0902',
    date: '2026-09-02',
    enabled: true,
    slots: [
      {
        documentId: 'slot-0902-0900',
        startTime: '09:00',
        endTime: '09:30',
        enabled: true,
        quota: 10,
        usedCount: 3,
        holdCount: 0,
        remaining: 7,
      },
      {
        documentId: 'slot-0902-0930',
        startTime: '09:30',
        endTime: '10:00',
        enabled: true,
        quota: 10,
        usedCount: 1,
        holdCount: 0,
        remaining: 9,
      },
    ],
  },
  {
    documentId: 'event-date-0903',
    date: '2026-09-03',
    enabled: true,
    slots: [
      {
        documentId: 'slot-0903-0900',
        startTime: '09:00',
        endTime: '09:30',
        enabled: true,
        quota: 10,
        usedCount: 0,
        holdCount: 0,
        remaining: 10,
      },
    ],
  },
];

export const events: EventListItemDTO[] = [
  {
    documentId: 'event-hsbc-2026-flu',
    eventCode: '2026-flu-vaccination',
    companyName: 'HSBC',
    location: 'Central Main Building',
    eventName: '2026 Flu Vaccination',
    description: 'Flu vaccination service for HSBC employees',
    notes: 'Please do not eat in the morning.',
    partitionCode: 'HSBC-FLU',
    status: 'RELEASED',
    registrationStartDate: '2026-08-01',
    registrationEndDate: '2026-08-30',
    eventStartDate: '2026-09-01',
    eventEndDate: '2026-09-03',
    dayStartTime: '09:00',
    dayEndTime: '18:00',
    reminderOffsetDays: 2,
    publicUrl: '/p/HSBC-FLU/e/2026-flu-vaccination',
    qrPayload: 'https://erp.local/p/HSBC-FLU/e/2026-flu-vaccination',
  },
  {
    documentId: 'event-hsbc-2026-backup',
    eventCode: '2026-backup-vaccination-day',
    companyName: 'HSBC',
    location: 'Kowloon Office',
    eventName: '2026 Backup Vaccination Day',
    description: 'Standby event kept visible but not bookable',
    notes: 'Disabled event example',
    partitionCode: 'HSBC-FLU',
    status: 'DISABLED',
    registrationStartDate: '2026-09-10',
    registrationEndDate: '2026-09-12',
    eventStartDate: '2026-09-15',
    eventEndDate: '2026-09-15',
    dayStartTime: '09:00',
    dayEndTime: '18:00',
    reminderOffsetDays: 2,
    publicUrl: '/p/HSBC-FLU/e/2026-backup-vaccination-day',
    qrPayload: 'https://erp.local/p/HSBC-FLU/e/2026-backup-vaccination-day',
  },
  {
    documentId: 'event-hase-2026-flu',
    eventCode: '2026-staff-flu-vaccination',
    companyName: 'HASE',
    location: 'Mong Kok Clinic',
    eventName: '2026 Staff Flu Vaccination',
    description: 'HASE campaign sample',
    notes: 'Bring staff card.',
    partitionCode: 'HASE-FLU',
    status: 'RELEASED',
    registrationStartDate: '2026-03-15',
    registrationEndDate: '2026-04-20',
    eventStartDate: '2026-04-18',
    eventEndDate: '2026-04-18',
    dayStartTime: '09:00',
    dayEndTime: '18:00',
    reminderOffsetDays: 2,
    publishedToPortals: true,
    publicUrl: '/p/HASE-FLU/e/2026-staff-flu-vaccination',
    qrPayload: 'https://erp.local/p/HASE-FLU/e/2026-staff-flu-vaccination',
  },
];

export const eventDetails: Record<string, EventDetailDTO> = {
  'event-hsbc-2026-flu': {
    event: {
      ...events[0],
      fields: systemFields,
      dates: hsbcEventDates.map((date) => ({ ...date })),
      notifications: [
        {
          type: 'REGISTRATION',
          templateDocumentId: 'notice-template-registration-email',
          templateName: 'Registration Email',
          channel: 'EMAIL',
          subject: 'HSBC flu vaccination booking confirmed',
          enabled: true,
        },
        {
          type: 'ANNOUNCEMENT',
          templateDocumentId: 'notice-template-announcement-email',
          templateName: 'Announcement Email',
          channel: 'EMAIL',
          subject: 'HSBC flu vaccination announcement',
          enabled: true,
        },
        {
          type: 'EVENT_UPDATE',
          templateDocumentId: 'notice-template-event-update-email',
          templateName: 'Event Update Email',
          channel: 'EMAIL',
          subject: 'HSBC flu vaccination event update',
          enabled: true,
        },
      ],
    },
  },
  'event-hsbc-2026-backup': {
    event: {
      ...events[1],
      fields: systemFields,
      dates: [
        {
          documentId: 'event-date-backup',
          date: '2026-09-15',
          enabled: true,
          slots: [
            {
              documentId: 'slot-backup-0900',
              startTime: '09:00',
              endTime: '09:30',
              enabled: true,
              quota: 8,
              usedCount: 0,
              holdCount: 0,
              remaining: 8,
            },
          ],
        },
      ],
      notifications: [],
    },
  },
  'event-hase-2026-flu': {
    event: {
      ...events[2],
      fields: systemFields,
      dates: [
        {
          documentId: 'hase-date-1',
          date: '2026-04-18',
          enabled: true,
          slots: [
            {
              documentId: 'hase-slot-1',
              startTime: '14:00',
              endTime: '14:30',
              enabled: true,
              quota: 12,
              usedCount: 7,
              holdCount: 0,
              remaining: 5,
            },
          ],
        },
      ],
      notifications: [],
    },
  },
};

export const appointments: AppointmentDTO[] = [
  {
    documentId: 'appointment-001',
    bookingReference: 'HSBC-2026-0001',
    eventDocumentId: 'event-hsbc-2026-flu',
    eventName: '2026 Flu Vaccination',
    companyName: 'HSBC',
    participantName: 'Chan Tai Man',
    staffNumber: '43791500',
    medicalCardNumber: 'AB12345',
    hkidPrefix: 'A123',
    registeredEmail: 'testing@hsbc.com',
    mobileNumber: '67180938',
    communicationPreference: 'EMAIL',
    status: 'CONFIRMED',
    appointmentDate: '2026-09-01',
    appointmentStartTime: '09:00',
    appointmentEndTime: '09:30',
    quota: 10,
    remainingAfterBooking: 7,
    cancelToken: 'cancel-001',
    portalSource: 'ERP',
  },
  {
    documentId: 'appointment-002',
    bookingReference: 'HSBC-2026-0002',
    eventDocumentId: 'event-hsbc-2026-flu',
    eventName: '2026 Flu Vaccination',
    companyName: 'HSBC',
    participantName: 'Lee Ka Yan',
    staffNumber: '58390124',
    registeredEmail: 'lee.kayan@hsbc.com.hk',
    mobileNumber: '61234567',
    communicationPreference: 'SMS',
    status: 'CONFIRMED',
    appointmentDate: '2026-09-01',
    appointmentStartTime: '09:30',
    appointmentEndTime: '10:00',
    quota: 10,
    remainingAfterBooking: 6,
    cancelToken: 'cancel-002',
    portalSource: 'ERP',
  },
  {
    documentId: 'appointment-003',
    bookingReference: 'HSBC-2026-0003',
    eventDocumentId: 'event-hsbc-2026-flu',
    eventName: '2026 Flu Vaccination',
    companyName: 'HSBC',
    participantName: 'Wong Mei Ling',
    staffNumber: '99881234',
    registeredEmail: 'wong.ml@hsbc.com.hk',
    communicationPreference: 'EMAIL',
    status: 'CANCELLED',
    appointmentDate: '2026-09-02',
    appointmentStartTime: '09:00',
    appointmentEndTime: '09:30',
    quota: 10,
    portalSource: 'EAP',
  },
];

export const documents: PortalDocumentDTO[] = [
  {
    documentId: 'doc-prep',
    titleEn: 'Vaccination Preparation Guide',
    titleZh: '接種前須知',
    portalTargets: ['EAP', 'ECP', 'ERP'],
    fileName: 'vaccination-preparation-guide.pdf',
    downloadUrl: '/uploads/vaccination-preparation-guide.pdf',
    partitionCode: 'HSBC-FLU',
  },
  {
    documentId: 'doc-admin-ops',
    titleEn: 'HR Operations Checklist',
    titleZh: '人力資源操作清單',
    portalTargets: ['EAP', 'ECP'],
    fileName: 'hr-operations-checklist.pdf',
    downloadUrl: '/uploads/hr-operations-checklist.pdf',
  },
];

export const contacts: ContactInfoDTO[] = [
  {
    documentId: 'contact-qhms-main',
    titleEn: 'QHMS Support Desk',
    titleZh: 'QHMS 支援服務台',
    email: 'support@qhms.com',
    phone: '+852 1234 5678',
    addressEn: '12/F, Wellness Tower, Central, Hong Kong',
    addressZh: '香港中環康健大樓 12 樓',
    portalTargets: ['EAP', 'ECP', 'ERP'],
  },
];

export const partitionLandings: Record<string, PartitionLandingDTO> = {
  'HSBC-FLU': {
    partition: partitions[0],
    events: events.filter((event) => event.partitionCode === 'HSBC-FLU' && event.status !== 'CLOSED'),
    documents: documents.filter((doc) => !doc.partitionCode || doc.partitionCode === 'HSBC-FLU'),
    contacts,
  },
  'HASE-FLU': {
    partition: partitions[1],
    events: events.filter((event) => event.partitionCode === 'HASE-FLU' && event.status !== 'CLOSED'),
    documents,
    contacts,
  },
};

export const dashboards: Record<'eap' | 'ecp' | 'erp', DashboardDTO> = {
  eap: {
    headline: 'EAP overview',
    stats: [
      { label: 'Partitions', value: String(partitions.length), helper: 'Event access scopes' },
      { label: 'User groups', value: String(groups.length), helper: 'Portal access groups' },
      { label: 'Templates', value: String(templates.length), helper: 'Reusable event blueprints' },
      { label: 'Appointments', value: String(appointments.filter((item) => item.status === 'CONFIRMED').length), helper: 'Confirmed bookings' },
    ],
  },
  ecp: {
    headline: 'ECP overview',
    stats: [
      { label: 'Visible events', value: String(events.filter((item) => item.partitionCode === 'HSBC-FLU').length), helper: 'HSBC partition' },
      { label: 'Confirmed bookings', value: String(appointments.filter((item) => item.companyName === 'HSBC' && item.status === 'CONFIRMED').length), helper: 'Across visible events' },
      { label: 'Documents', value: String(documents.filter((doc) => doc.portalTargets.includes('ECP')).length), helper: 'Portal downloads' },
    ],
  },
  erp: {
    headline: 'ERP public landing',
    stats: [
      { label: 'Published events', value: String(partitionLandings['HSBC-FLU'].events.length), helper: 'For the selected partition' },
      { label: 'Downloadable files', value: String(documents.filter((doc) => doc.portalTargets.includes('ERP')).length), helper: 'Useful information' },
      { label: 'Support contacts', value: String(contacts.length), helper: 'Contact us' },
    ],
  },
};

export const sampleHold: HoldResponseDTO = {
  holdToken: 'hold-demo-token',
  expiresAt: new Date(Date.now() + 5 * 60 * 1000).toISOString(),
  remaining: 7,
  slotDocumentId: 'slot-0901-0900',
};

export function getEventDetail(documentId: string): EventDetailDTO | undefined {
  return Object.values(eventDetails).find((detail) => detail.event.documentId === documentId || detail.event.eventCode === documentId);
}

export function getPartitionLanding(partitionCode: string): PartitionLandingDTO | undefined {
  return partitionLandings[partitionCode];
}
